# Generated by Django 3.2.9 on 2021-12-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='stock',
            new_name='product_option',
        ),
    ]
