# Generated by Django 3.2.9 on 2021-12-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productset',
            old_name='item_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productset',
            old_name='set_name',
            new_name='product_set',
        ),
    ]
