# Generated by Django 3.2.9 on 2021-12-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211201_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keyword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
